---
title: "Spatial Models"
description: |
editor_options: 
  markdown: 
    wrap: 72
---

# Neighborhood Structure

Before we build a model to handle the spatial correlation between the regions, we need to first define the neighborhood structure, that is, how do we define whether two regions are spatially correlated. There are several ways to define a neighborhood and the most common one is the **Queen neighborhood structure**, meaning if the two polygons touch each other, even a point, they are neighbors. In the following discussion, we will apply this structure to the model. With the neighborhood structure, we can codify it with a spatial weighting matrix $W$. $W$ is a $n \times n$ matrix, where $n$ represents the number of regions. Here we are using a binary matrix, meaning the values $w_{ij}$ in the matrix are either 0 or 1. 0 means the region $i$ and region $j$ are not neighbors (no influence of $i$ on $j$) and 1 means they are. For the Queen neighborhood structure, the matrix is symmetric by the diagonal.

# BYM Model

The spatial model we are using here is the Besag-York-Mollie (BYM) model (Besag, York, and Mollie 1991). Here we assume the outcome variable ($Y_i$) can be modeled using a normal distribution. $i \in {1, 2, …, n}$ represents the regions we are investigating. The BYM model can be specified as

$$
\begin{array}
\text{Data: } & Y|\beta_0, \beta_k, \sigma \sim N(\mu_i, \sigma^2) \;\;
\text{ where } \mu_i = \beta_0 + \sum_{k=1}^k x_{ik} \beta_k + u_i + \epsilon_i \\
&& \\
\text{Priors: } & \beta_0 \sim N(m_0, s_0^2) \\
& \beta_k \sim N(m_k, s_k^2) \\
& \sigma \sim exp(l)\\
& u_i \sim u_i | u_j, j ≠ i \sim N(\sum_{j \in N_i} w_{ij}u_j, \sigma_i^2)\\
& \epsilon \sim N(0, \sigma_\epsilon^2)
\end{array}
$$

The model can be split into two components, fixed effect, $\beta_0 + x_{ik}\beta_k$, and random effect, $u_i + \epsilon_i$. For the fixed effect, $\beta_0$ is the intercept, $\beta_k$ is a set of coefficients of k predictors we are interested in. The random effect includes spatial random effect $u_i$ and non-spatial random effect $\epsilon_i$. Spatial random effect $u_i$ accounts for the spatial dependence between outcomes indicating the value of a region is correlated with the value of its neighbors. And the non-spatial random effect $\epsilon_i$ models the uncorrelated noise. In the BYM model, the spatial random effect $u_i$ is modeled by the intrinsic conditional autoregressive (ICAR) model. $N_i$ is the set of neighbors of region $i$, $n$ is the number of neighbors in this set $N_i$, and $j$ is the neighbor region with $j \in N_i$. We will discuss the CAR and ICAR model in detail in the following subsection.

### (Intrinsic) Conditional Autoregressive Model

The Conditional Autoregressive (CAR) model is one of the most widespread approaches for spatial modeling. It was first introduced by Besag (1974) and remains one of the most primary methods for areal data modeling. Generally, the CAR model relies on the binary neighborhood structure $W$, which we discussed earlier. The entries $w_{ij}$ is 1 if region $i$ and region $j$ are neighbors and 0 otherwise. The region is not considered to be the neighbor of itself, so $w_{ii}$, the entries on the diagonal, is 0.

In the BYM model, the spatial interaction between pairs of region $i$ and region $j$ is modeled conditionally as a set of spatial random effects $u = (u_1, u_2, …, u_N)$, $N$ represents the number of regions we are looking at. The distribution of u_i is determined by the sum of weighted values of its neighbors $w_{ij}u_j$. The model is specified as 

$$u_i | u_j, j ≠ i \sim N(\sum_{j \in N_i} \frac{w_{ij}u_j}{n}, \sigma_i^2)$$ 
In the model, $j$ is the neighbor region in the neighborhood set of region $i$, $N_i$. $n$ is the count of neighbors in the set $N_i$, and $\sigma_i$ is the unknown variance of random effect $u_i$.

Besag (1974) proved that the joint distribution of $u$ is a multivariate normal centered at 0. The variance of $u$ is specified as a precision matrix $Q$ which is the inverse of a covariance matrix. With that,
$$u \sim N(0, Q^{-1})$$ 
For the multivariate normal random variable $u$, the precision matrix $Q$ of CAR model is constructed from two matrices: diagonal matrix $D$ and adjacency matrix, which is the neighborhood matrix we defined above $W$. For CAR model, $Q$ is defined as 
$$Q = D(I - \alpha W)$$ 
where $I$ is the identity matrix, and $\alpha$ is a parameter in CAR model controlling the amount of spatial dependence and $0 < \alpha < 1$. $\alpha = 0$ means spatial independence, $\alpha = 1$ otherwise. For Intrinsic Conditional Autoregressive (ICAR) model, we set $\alpha$ is 1 and the precision matrix of ICAR model can be simplified as
$$Q = D - W$$

In the ICAR model, $u_i$ is normally distributed with the mean equal to the average of neighbor values. That is saying the spatial effect of region $i$ is determined by the mean of its neighbors' spatial effect. The conditional specification of ICAR model is 
$$u_i | u_j, i ≠ j \sim N(\frac{\sum_{j\in N_i}u_j}{n}, \frac{\sigma_i^2}{n})$$ 
$\frac{\sigma_i^2}{n}$ implies that the variance of spatial effect decreases as the number of neighbors increases. In other words, if the region has more neighbors, we are more confident in estimating its spatial effect.


# BYM2 Model
In the previous section, we discussed the BYM model. However, because of the lack of informative hyperpriors specific for $u$ and $\epsilon$, the BYM model could be challenging to fit. Riebler et al. (2016) further explained the issue of the BYM model that it has unnecessary long computation time when fitting the model. So, building on to the BYM model, the BYM2 model, described by Riebler et al. (2016) and Simpson et al. (2017), aims to solve these problems by adding new parameters $\rho$, $s$, $\sigma_c$. It is also the final model we are using in this project. Same as the BYM model, the BYM2 model also includes the spatial random effect and non-spatial random effect (noise), but placing those parameters on the error terms. $\sigma_c$ is a single scale parameter placed on the combined random effect terms, meaning the standard deviation of the combined error terms. $\rho \in [0, 1]$ is a mixing parameter for the proportion of variance coming from the spatial random effect. $s$ is a scaling factor scaling the proportion $\rho$ to make the standard deviation of the combined error terms $\sigma_c$ legitimately. With all those, the BYM2 model is specified as

$$
\begin{array}
\text{} & Y_i \sim N(\mu_i,\sigma^2)\;\;
\text{, where } \mu_i=\beta_0+\sum_{k=1}^k \beta_k x_{ik} + (\sqrt{\frac{\rho}{s}}u_i+\sqrt{1-\rho_i}\epsilon_i)\sigma_c\\
&&\\
\text{Priors: } & \beta_0 \sim N(m_0, s_0^2) \\
& \beta_k \sim N(m_k, s_k^2) \\
& \sigma \sim exp(l)\\
& u_i \sim u_i | u_j, i ≠ j \sim N(\frac{\sum_{j\in N_i}u_j}{n}, \frac{\sigma_i^2}{n})\\
& ε_i \sim N(0, n_s) \\
& \rho \sim Beta(0.5,0.5)\\
& \sigma_c \sim N(0,1)
\end{array}
$$

With all those theoretical background of the BYM2 model, in the following sections, we will apply it to real-world data for posterior simulation.
